apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: petclinic
          image: 15.206.146.149:8084/gradle1:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
